@endpoint = http://localhost:8000
@job = /convert/637e6e99167566f4514107d8?token=cYgdioz1JxYFd7Fg2ZHNZDsO8QMvJX
###
GET {{endpoint}}
###
POST {{endpoint}}/convert
Content-Type: application/json

< example.json
###
GET {{endpoint}}{{job}}
###
POST {{endpoint}}/preview
Content-Type: application/pdf

< samples/pdf-example-encryption.pdf
###
POST {{endpoint}}/preview
Content-Type: application/pdf

< samples/sample06.pdf