[package]
name = "pdftransform"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = {version = "0.5.0-rc.2", features = ["json"]}
mongodb = "2.3"
bson = { version = "2", features = ["chrono-0_4"] }
tokio = "1"
chrono = "0.4"
serde = "1"
serde_repr = "0.1"
serde_type_name = "0.2.0"
reqwest = "0.11"
bytes = "1.2"
futures = {version = "0.3.24"}
tempfile = "3.3.0"