version: '3'
services:
  mongodb:
    image: mongo:6.0.2
  pdftransform:
    build: .
    environment:
      ROCKET_DATABASES: '{db={url="mongodb://mongodb:27017"}}'
    ports:
      - 8000:8000
    depends_on:
      - mongodb
