version: '3'
services:
  nats:
    image: nats:scratch
    command: "-js -DV"
  mongodb:
    image: mongo:6.0.5
    # ports:
    #   - 27017:27017
    depends_on:
      - nats
  service:
    build:
      context: .
      dockerfile: ./service/Dockerfile
    environment:
      MONGO_URI: mongodb://mongodb:27017
      NATS_URI: nats://nats:4222
    ports:
      - 8000:8000
    depends_on:
      - mongodb
      - nats
  transform:
    build:
      context: .
      dockerfile: ./transform/Dockerfile
    environment:
      MONGO_URI: mongodb://mongodb:27017
      NATS_URI: nats://nats:4222
    depends_on:
      - mongodb
      - nats
  preview:
    build:
      context: .
      dockerfile: ./preview/Dockerfile
    environment:
      MONGO_URI: mongodb://mongodb:27017
      NATS_URI: nats://nats:4222
    depends_on:
      - mongodb
      - nats
  # test:
  #   build:
  #     context: .
  #     dockerfile: ./test/Dockerfile
  #   tty: true
