version: '3'
services:
  mongodb:
    image: mongo:6.0.2
  pdftransform:
    build: .
    environment:
      MONGO_URI: mongodb://mongodb:27017
    ports:
      - 8000:8000
    depends_on:
      - mongodb
