[package]
name = "preview"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
async-trait = "0.1.68"
tokio = "1.27.0"
reqwest = {version = "0.11.18", default-features = false, features = ["gzip", "deflate", "stream", "json", "rustls-tls"]}
pdfium-render = {version = "0.7.34", features = ["sync"]}
image = "0.24.6"
mime = "0.3.17"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["json"] }

[features]

static = ["pdfium-render/static", "pdfium-render/libc++"]