[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
bson = { version = "2.6.1", features = ["chrono-0_4"] }
chrono = "0.4.26"
serde = { version = "1.0.177", features = ["derive"] }
serde_repr = "0.1.16"
serde_json = "1.0.104"
async-trait = "0.1.72"
mongodb = "2.6.0"
mongodb-gridfs = "0.2.5"
tokio = { version = "1.29.1", features = ["fs"]}
mime = "0.3.17"
tracing = "0.1.37"
futures = {version = "0.3.28"}
rand = "0.8.5"
base64 = "0.21.2"
tokio-util = "0.7.8"
tokio-stream = "0.1.14"
async-nats = "0.31.0"
reqwest = {version = "0.11.18", default-features = false, features = ["gzip", "deflate", "stream", "json", "rustls-tls"]}
bytes = "1.4.0"
