version: '3'
services:
  nats:
    image: nats:2.9.20-scratch
    command: "-js -DV -sd /data"
    volumes:
      - ./data/nats/:/data
    ports:
      - 4222:4222
  minio:
    image: quay.io/minio/minio:RELEASE.2023-07-21T21-12-44Z
    entrypoint: sh
    command: -c 'mkdir -p /data/bucket && minio server --console-address ":9001" /data'
    volumes:
      - ./data/minio/:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_BUCKET_NAME: bucket
      MINIO_REGION: us-east-1
      MINIO_ROOT_USER: minio123
      MINIO_ROOT_PASSWORD: minio123
