version: '3'
services:
  nats:
    image: nats:2.9.20-scratch
    command: "-js -DV -sd /data"
    volumes:
      - ./data/nats/:/data
    ports:
      - 4222:4222
  minio:
    image: quay.io/minio/minio:RELEASE.2023-07-21T21-12-44Z
    command: server --console-address ":9001" /data
    volumes:
      - ./data/minio/:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: "acces_key"
      MINIO_SECRET_KEY: "secret_key"
      MINIO_BUCKET_NAME: "bucket"
      MINIO_REGION: region

# S3_ACCESS_KEY_ID:
# S3_SECRET_ACCESS_KEY:
# S3_REGION:
# S3_ENDPOINT:
# S3_BUCKET